### ISSUE TITLE
Default Account Access issue

### ISSUE THREAD

**Issue by YeaminRabbi** [takielias/tablar-demo-project#1]
![image](https://github.com/takielias/tablar-demo-project/assets/44961810/d94f6be2-75b5-4350-932d-58a247e66273)
![image](https://github.com/takielias/tablar-demo-project/assets/44961810/aeb7188b-4186-4dba-83c1-b14c5707e8a8)

please check the default value in the site for login is not working

**Comment by takielias** [comment]
@YeaminRabbi Did you setup db in your .env file? Did you run migrate command?

**Comment by YeaminRabbi** [comment]
I was browsing in the live site 

https://tablar.ebuz.xyz/login

**Comment by iamsaddamhussain** [comment]
Same for me as well

**Comment by takielias** [comment]
@YeaminRabbi @iamsaddamhussain  Fixed. Please check.

**Comment by YeaminRabbi** [comment]
Thanks, solved
