### ISSUE TITLE
Dark Mode - DataTable

### ISSUE THREAD

**Issue by YeaminRabbi** [takielias/tablar-demo-project#2]
![image](https://github.com/takielias/tablar-demo-project/assets/44961810/d1fe6123-f99d-403d-b262-4d2719a77cd4)
Please check for the data in the table while darkmode, it may depend on the theme of browser still check!

**Comment by takielias** [comment]
@YeaminRabbi Yes, I have already got it. Feel free to make a PR for the fix.
